//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathPath.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
        public Entities(string connection)
            : base(connection)
        {
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Degree> Degrees { get; set; }
        public virtual DbSet<Path> Paths { get; set; }
        public virtual DbSet<Placement> Placements { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<ProgramPath> ProgramPaths { get; set; }
        public virtual DbSet<MajorList> MajorLists { get; set; }
        public virtual DbSet<ProgramPathName> ProgramPathNames { get; set; }
    }
}
