//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathPath.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Path()
        {
            this.ProgramPaths = new HashSet<ProgramPath>();
        }
    
        public int PathId { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Courses { get; set; }
        public bool AllowTestOut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProgramPath> ProgramPaths { get; set; }
    }
}
