//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MathPath.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Placement
    {
        public int PlacementId { get; set; }
        public string Aleks { get; set; }
        public string Act { get; set; }
        public string Sat { get; set; }
        public string Accuplacer { get; set; }
        public Nullable<int> PlacementLevel { get; set; }
    }
}
